#Demo user and secret keys for testing purposes. In a real application, these would be securely stored and managed.
automation.user1=JBSWY3DPEHPK3PXP 
automation.user2=KRSXG5DSMFZXGIDM 
automation.admin=GEZDGNBVGY3TQOJQ
