<<<<<<< HEAD
#Demo user and secret keys for testing purposes. In a real application, these would be securely stored and managed.
automation.user1=JBSWY3DPEHPK3PXP 
automation.user2=KRSXG5DSMFZXGIDM 
automation.admin=GEZDGNBVGY3TQOJQ
 
=======
automation.user1=JBSWY3DPEHPK3PXP #Demo user and secret key
automation.user2=KRSXG5DSMFZXGIDM #Demo user and secret key
automation.admin=GEZDGNBVGY3TQOJQ #Demo user and secret key
>>>>>>> c5cf6bc4fb57a23c1261f95780232b54ece7d843
